-- Legacy reference only.
--
-- The canonical WonderWord AI database schema is version-controlled in:
--
--   supabase/migrations/
--
-- Do not apply this file to a Supabase project and do not add new schema here.
-- Create a new migration with the Supabase CLI instead, then verify it with:
--
--   npx supabase db reset
--   npx supabase db lint
--   npx supabase test db
--
-- This placeholder intentionally contains no executable schema so the legacy
-- infra path cannot drift silently from the migration history.
