-- Word of the Day: 366 curated words, one per day of the year.
--
-- Kid-friendly vocabulary (grades 1-5) with a short definition and an example
-- sentence. The Child Home reads the row matching the current day of the year,
-- so every login day shows a different word. No external API involved.

INSERT INTO public.words_of_the_day (day_of_year, word, part_of_speech, definition, example_sentence)
VALUES
    (1,   'Brave',       'adjective', 'Being brave means doing something even when you feel scared.', 'The brave puppy walked right past the big dog.'),
    (2,   'Giggle',      'verb',      'To giggle is to laugh in a small, silly way.', 'We giggle every time the clown trips.'),
    (3,   'Sparkle',     'verb',      'To sparkle is to shine with tiny flashes of light.', 'The stars sparkle above our tent.'),
    (4,   'Curious',     'adjective', 'Feeling curious means you want to learn more about something.', 'Maya is curious about how bees make honey.'),
    (5,   'Wobble',      'verb',      'To wobble is to move side to side without being steady.', 'The tall tower of blocks began to wobble.'),
    (6,   'Gentle',      'adjective', 'Gentle means soft and careful, not rough.', 'Give the kitten a gentle pat.'),
    (7,   'Enormous',    'adjective', 'Enormous means very, very big.', 'An enormous whale swam past the boat.'),
    (8,   'Whisper',     'verb',      'To whisper is to speak in a very quiet voice.', 'I whisper secrets to my best friend.'),
    (9,   'Journey',     'noun',      'A journey is a trip from one place to another.', 'Our journey to the beach took two hours.'),
    (10,  'Clever',      'adjective', 'Clever means smart and quick at figuring things out.', 'The clever fox found a way over the fence.'),
    (11,  'Shiver',      'verb',      'To shiver is to shake a little because you are cold or scared.', 'I shiver when the cold wind blows.'),
    (12,  'Bloom',       'verb',      'To bloom is to open up into a flower.', 'The roses bloom every spring.'),
    (13,  'Munch',       'verb',      'To munch is to chew food in a noisy way.', 'Rabbits munch on crunchy carrots.'),
    (14,  'Puzzle',      'noun',      'A puzzle is a game or problem you have to figure out.', 'This puzzle has one hundred pieces.'),
    (15,  'Shadow',      'noun',      'A shadow is the dark shape made when something blocks the light.', 'My shadow is taller in the evening.'),
    (16,  'Bounce',      'verb',      'To bounce is to spring back up after hitting something.', 'Watch the ball bounce off the wall.'),
    (17,  'Proud',       'adjective', 'Feeling proud means feeling happy about something you did well.', 'Dad is proud of my reading.'),
    (18,  'Tangle',      'noun',      'A tangle is a messy knot of things twisted together.', 'My kite string is in a tangle.'),
    (19,  'Explore',     'verb',      'To explore is to look around a new place to find out what is there.', 'We explore the woods behind the school.'),
    (20,  'Cozy',        'adjective', 'Cozy means warm, soft and comfortable.', 'The cat found a cozy spot by the fire.'),
    (21,  'Crumble',     'verb',      'To crumble is to break into tiny pieces.', 'The cookie began to crumble in my hand.'),
    (22,  'Mighty',      'adjective', 'Mighty means very strong and powerful.', 'A mighty oak grows in the park.'),
    (23,  'Glimmer',     'verb',      'To glimmer is to shine with a faint, soft light.', 'Fireflies glimmer in the dark garden.'),
    (24,  'Scamper',     'verb',      'To scamper is to run with quick, light steps.', 'Squirrels scamper up the tree.'),
    (25,  'Friendly',    'adjective', 'Friendly means kind and nice to other people.', 'Our new neighbour is very friendly.'),
    (26,  'Thunder',     'noun',      'Thunder is the loud rumble you hear after lightning.', 'The thunder made the windows rattle.'),
    (27,  'Invent',      'verb',      'To invent is to make something that never existed before.', 'I want to invent a robot that folds clothes.'),
    (28,  'Slippery',    'adjective', 'Slippery means smooth and hard to hold or walk on.', 'The icy path is very slippery.'),
    (29,  'Treasure',    'noun',      'A treasure is something valuable that people want to keep.', 'We buried our treasure in the sandbox.'),
    (30,  'Peek',        'verb',      'To peek is to look quickly and secretly.', 'Do not peek at your birthday present!'),
    (31,  'Cheerful',    'adjective', 'Cheerful means happy and full of good feelings.', 'Her cheerful song made us all smile.'),
    (32,  'Rumble',      'verb',      'To rumble is to make a low, rolling sound.', 'My tummy starts to rumble before lunch.'),
    (33,  'Mysterious',  'adjective', 'Mysterious means strange and hard to explain.', 'A mysterious light shone in the cave.'),
    (34,  'Flutter',     'verb',      'To flutter is to move with quick, light flaps.', 'Butterflies flutter over the flowers.'),
    (35,  'Brilliant',   'adjective', 'Brilliant means very bright, or very clever.', 'That was a brilliant idea!'),
    (36,  'Squeeze',     'verb',      'To squeeze is to press something tightly.', 'Squeeze the lemon to get the juice.'),
    (37,  'Wander',      'verb',      'To wander is to walk around slowly with no plan.', 'We wander through the busy market.'),
    (38,  'Delicious',   'adjective', 'Delicious means something tastes really good.', 'Grandma made a delicious apple pie.'),
    (39,  'Shelter',     'noun',      'A shelter is a place that keeps you safe from weather or danger.', 'The birds found shelter under the roof.'),
    (40,  'Wiggle',      'verb',      'To wiggle is to move side to side in small, quick moves.', 'The puppy wiggles when he is happy.'),
    (41,  'Ancient',     'adjective', 'Ancient means very, very old.', 'We saw an ancient castle on the hill.'),
    (42,  'Echo',        'noun',      'An echo is a sound that bounces back to you.', 'My shout made an echo in the tunnel.'),
    (43,  'Gather',      'verb',      'To gather is to bring things or people together.', 'We gather leaves for our art project.'),
    (44,  'Splendid',    'adjective', 'Splendid means wonderful and very nice.', 'What a splendid day for a picnic!'),
    (45,  'Tumble',      'verb',      'To tumble is to fall and roll over.', 'The kittens tumble across the rug.'),
    (46,  'Rescue',      'verb',      'To rescue is to save someone from danger.', 'Firefighters rescue the cat from the tree.'),
    (47,  'Narrow',      'adjective', 'Narrow means thin from one side to the other.', 'We walked down a narrow path.'),
    (48,  'Dazzle',      'verb',      'To dazzle is to shine so brightly that it surprises you.', 'The fireworks dazzle the whole crowd.'),
    (49,  'Quiver',      'verb',      'To quiver is to shake with tiny, fast movements.', 'The leaf began to quiver in the breeze.'),
    (50,  'Wonder',      'noun',      'Wonder is the amazed feeling you get from something special.', 'The night sky filled us with wonder.'),
    (51,  'Scribble',    'verb',      'To scribble is to write or draw quickly and messily.', 'I scribble notes in my notebook.'),
    (52,  'Stubborn',    'adjective', 'Stubborn means not wanting to change your mind.', 'My stubborn dog will not move.'),
    (53,  'Glide',       'verb',      'To glide is to move smoothly without any effort.', 'Swans glide across the still lake.'),
    (54,  'Hollow',      'adjective', 'Hollow means empty on the inside.', 'An owl lives in the hollow tree.'),
    (55,  'Joyful',      'adjective', 'Joyful means full of happiness.', 'The joyful crowd sang together.'),
    (56,  'Drift',       'verb',      'To drift is to float along slowly.', 'Clouds drift across the blue sky.'),
    (57,  'Sturdy',      'adjective', 'Sturdy means strong and not easy to break.', 'We built a sturdy bridge from blocks.'),
    (58,  'Marvel',      'verb',      'To marvel is to be filled with surprise and admiration.', 'We marvel at the huge waterfall.'),
    (59,  'Crisp',       'adjective', 'Crisp means firm and it breaks with a snap.', 'I love a crisp green apple.'),
    (60,  'Hurry',       'verb',      'To hurry is to move quickly because there is little time.', 'We hurry to catch the bus.'),
    (61,  'Cuddle',      'verb',      'To cuddle is to hold someone close in a warm way.', 'I cuddle my teddy at bedtime.'),
    (62,  'Peculiar',    'adjective', 'Peculiar means odd or unusual.', 'That is a peculiar hat!'),
    (63,  'Blossom',     'noun',      'A blossom is a flower on a tree or plant.', 'Pink blossom covered the whole branch.'),
    (64,  'Clatter',     'verb',      'To clatter is to make a loud, rattling noise.', 'The pans clatter when they fall.'),
    (65,  'Patient',     'adjective', 'Being patient means waiting calmly without getting upset.', 'Be patient, the cake needs more time.'),
    (66,  'Plunge',      'verb',      'To plunge is to jump or fall suddenly into something.', 'The diver plunged into the deep pool.'),
    (67,  'Gleam',       'verb',      'To gleam is to shine softly and smoothly.', 'The clean windows gleam in the sun.'),
    (68,  'Grumble',     'verb',      'To grumble is to complain in a low voice.', 'He grumbles about doing the dishes.'),
    (69,  'Swift',       'adjective', 'Swift means very fast.', 'A swift rabbit dashed across the field.'),
    (70,  'Blanket',     'noun',      'A blanket is a warm cover you put over yourself.', 'She pulled the blanket up to her chin.'),
    (71,  'Amaze',       'verb',      'To amaze is to surprise someone in a wonderful way.', 'Magic tricks amaze my little brother.'),
    (72,  'Crooked',     'adjective', 'Crooked means bent or not straight.', 'The old garden fence is crooked.'),
    (73,  'Nibble',      'verb',      'To nibble is to take tiny bites.', 'Mice nibble the cheese.'),
    (74,  'Courage',     'noun',      'Courage is the strength to do something scary.', 'It took courage to speak on stage.'),
    (75,  'Howl',        'verb',      'To howl is to make a long, loud cry.', 'Wolves howl at the moon.'),
    (76,  'Tidy',        'adjective', 'Tidy means neat and in the right place.', 'Her desk is always tidy.'),
    (77,  'Glisten',     'verb',      'To glisten is to shine because something is wet.', 'Raindrops glisten on the grass.'),
    (78,  'Sprout',      'verb',      'To sprout is to start to grow.', 'The seeds sprout after a few days.'),
    (79,  'Vanish',      'verb',      'To vanish is to disappear suddenly.', 'The coin seemed to vanish from his hand.'),
    (80,  'Thrilled',    'adjective', 'Thrilled means very excited and happy.', 'I am thrilled about the school trip.'),
    (81,  'Murmur',      'verb',      'To murmur is to speak softly and low.', 'The little stream murmurs over the rocks.'),
    (82,  'Rugged',      'adjective', 'Rugged means rough and uneven.', 'We hiked up a rugged hill.'),
    (83,  'Dawn',        'noun',      'Dawn is the time when the sun first comes up.', 'Birds start singing at dawn.'),
    (84,  'Flicker',     'verb',      'To flicker is to shine on and off quickly.', 'The candle began to flicker.'),
    (85,  'Loyal',       'adjective', 'Loyal means always staying true to someone.', 'A loyal friend sticks by you.'),
    (86,  'Blustery',    'adjective', 'Blustery means very windy.', 'It was a blustery autumn morning.'),
    (87,  'Crumb',       'noun',      'A crumb is a tiny piece of bread or cake.', 'A hungry bird ate every crumb.'),
    (88,  'Dangle',      'verb',      'To dangle is to hang loosely and swing.', 'My feet dangle from the tall chair.'),
    (89,  'Eager',       'adjective', 'Eager means really wanting to do something.', 'The class is eager to start the game.'),
    (90,  'Fetch',       'verb',      'To fetch is to go and bring something back.', 'My dog can fetch the ball.'),
    (91,  'Glow',        'verb',      'To glow is to give off a soft, steady light.', 'The lamp glows in the corner.'),
    (92,  'Hush',        'noun',      'A hush is a sudden quiet.', 'A hush fell over the whole room.'),
    (93,  'Icicle',      'noun',      'An icicle is a pointed piece of hanging ice.', 'A long icicle hung from the roof.'),
    (94,  'Jolly',       'adjective', 'Jolly means cheerful and full of fun.', 'The jolly farmer waved at us.'),
    (95,  'Kindness',    'noun',      'Kindness is being caring and helpful to others.', 'Her kindness made my day better.'),
    (96,  'Lantern',     'noun',      'A lantern is a light you can carry.', 'We carried a lantern into the cave.'),
    (97,  'Meadow',      'noun',      'A meadow is a field full of grass and flowers.', 'Butterflies fly over the meadow.'),
    (98,  'Nestle',      'verb',      'To nestle is to settle in comfortably and safely.', 'The chicks nestle under their mother.'),
    (99,  'Orchard',     'noun',      'An orchard is a place where fruit trees grow.', 'We picked apples in the orchard.'),
    (100, 'Pebble',      'noun',      'A pebble is a small, smooth stone.', 'I skipped a pebble across the pond.'),
    (101, 'Quest',       'noun',      'A quest is a long search for something important.', 'The knight went on a brave quest.'),
    (102, 'Ripple',      'noun',      'A ripple is a small wave on water.', 'One drop made a ripple in the pond.'),
    (103, 'Stumble',     'verb',      'To stumble is to trip and almost fall.', 'I stumble over the loose rug.'),
    (104, 'Twirl',       'verb',      'To twirl is to spin around quickly.', 'Dancers twirl on the bright stage.'),
    (105, 'Useful',      'adjective', 'Useful means helpful for doing something.', 'A map is useful on a long hike.'),
    (106, 'Valley',      'noun',      'A valley is the low land between two hills.', 'A river runs through the valley.'),
    (107, 'Weary',       'adjective', 'Weary means very tired.', 'The weary hikers sat down to rest.'),
    (108, 'Yawn',        'verb',      'To yawn is to open your mouth wide when you are sleepy.', 'I yawn every night at eight.'),
    (109, 'Zigzag',      'verb',      'To zigzag is to move in sharp turns left and right.', 'The path zigzags up the mountain.'),
    (110, 'Anchor',      'noun',      'An anchor is a heavy hook that keeps a boat in place.', 'The sailors dropped the anchor.'),
    (111, 'Breeze',      'noun',      'A breeze is a light, gentle wind.', 'A cool breeze moved the curtains.'),
    (112, 'Chatter',     'verb',      'To chatter is to talk quickly about small things.', 'The monkeys chatter in the trees.'),
    (113, 'Drowsy',      'adjective', 'Drowsy means sleepy and slow.', 'The warm room made me drowsy.'),
    (114, 'Envelope',    'noun',      'An envelope is a paper cover for a letter.', 'She sealed the envelope carefully.'),
    (115, 'Feast',       'noun',      'A feast is a big, special meal.', 'We had a feast on my birthday.'),
    (116, 'Gaze',        'verb',      'To gaze is to look at something for a long time.', 'We gaze at the stars from the roof.'),
    (117, 'Harvest',     'noun',      'A harvest is the crops gathered when they are ready.', 'The harvest filled ten big baskets.'),
    (118, 'Imagine',     'verb',      'To imagine is to make a picture in your mind.', 'Imagine a house made of candy.'),
    (119, 'Jungle',      'noun',      'A jungle is a thick forest with many plants and animals.', 'Loud parrots live in the jungle.'),
    (120, 'Knight',      'noun',      'A knight was a soldier who wore armour and rode a horse.', 'The knight rode back to the castle.'),
    (121, 'Lively',      'adjective', 'Lively means full of energy.', 'The new puppies are very lively.'),
    (122, 'Mumble',      'verb',      'To mumble is to speak so softly it is hard to hear.', 'Do not mumble, speak up!'),
    (123, 'Nectar',      'noun',      'Nectar is the sweet juice inside flowers.', 'Bees collect nectar all day long.'),
    (124, 'Observe',     'verb',      'To observe is to watch something carefully.', 'We observe the ants building a nest.'),
    (125, 'Polite',      'adjective', 'Polite means using kind words and good manners.', 'It is polite to say thank you.'),
    (126, 'Quaint',      'adjective', 'Quaint means old-fashioned in a charming way.', 'We stayed in a quaint little cottage.'),
    (127, 'Roam',        'verb',      'To roam is to move around freely over a wide area.', 'Wild horses roam across the plain.'),
    (128, 'Sizzle',      'verb',      'To sizzle is to make a hissing sound while cooking.', 'The pancakes sizzle in the pan.'),
    (129, 'Trudge',      'verb',      'To trudge is to walk slowly with heavy steps.', 'We trudge home through deep snow.'),
    (130, 'Unusual',     'adjective', 'Unusual means not common or normal.', 'A purple carrot is unusual.'),
    (131, 'Vast',        'adjective', 'Vast means extremely large in size.', 'The desert is vast and empty.'),
    (132, 'Whirl',       'verb',      'To whirl is to spin around very fast.', 'Leaves whirl in the autumn wind.'),
    (133, 'Yearn',       'verb',      'To yearn is to want something very much.', 'I yearn for the summer holidays.'),
    (134, 'Zoom',        'verb',      'To zoom is to move very fast with a loud sound.', 'Race cars zoom around the track.'),
    (135, 'Applaud',     'verb',      'To applaud is to clap to show you liked something.', 'We applaud after the school play.'),
    (136, 'Boulder',     'noun',      'A boulder is a very large rock.', 'A huge boulder blocked the road.'),
    (137, 'Cavern',      'noun',      'A cavern is a big cave.', 'Bats sleep inside the dark cavern.'),
    (138, 'Daring',      'adjective', 'Daring means bold and willing to take a risk.', 'The daring climber reached the top.'),
    (139, 'Endless',     'adjective', 'Endless means it seems to go on forever.', 'The road ahead looked endless.'),
    (140, 'Fragile',     'adjective', 'Fragile means easy to break.', 'Handle the fragile eggs with care.'),
    (141, 'Grateful',    'adjective', 'Grateful means thankful for something.', 'I am grateful for my friends.'),
    (142, 'Hurdle',      'noun',      'A hurdle is a small fence you jump over.', 'She jumped the last hurdle and won.'),
    (143, 'Instant',     'noun',      'An instant is a very short moment of time.', 'The cat vanished in an instant.'),
    (144, 'Jagged',      'adjective', 'Jagged means having a rough, pointy edge.', 'The broken shell had a jagged edge.'),
    (145, 'Kernel',      'noun',      'A kernel is the soft seed inside a hard shell.', 'A popcorn kernel popped in the pot.'),
    (146, 'Lofty',       'adjective', 'Lofty means very tall or very high.', 'Lofty pine trees line the road.'),
    (147, 'Marsh',       'noun',      'A marsh is soft, wet ground with tall grass.', 'Frogs sing in the marsh at night.'),
    (148, 'Nimble',      'adjective', 'Nimble means able to move quickly and lightly.', 'The nimble cat leapt to the shelf.'),
    (149, 'Outstanding', 'adjective', 'Outstanding means much better than usual.', 'Her drawing was outstanding.'),
    (150, 'Pounce',      'verb',      'To pounce is to jump suddenly onto something.', 'The kitten will pounce on the string.'),
    (151, 'Quench',      'verb',      'To quench is to drink until you are not thirsty.', 'Cold water will quench your thirst.'),
    (152, 'Radiant',     'adjective', 'Radiant means shining brightly with light or joy.', 'Her radiant smile lit up the room.'),
    (153, 'Scurry',      'verb',      'To scurry is to run with short, hurried steps.', 'Mice scurry under the floorboards.'),
    (154, 'Timid',       'adjective', 'Timid means shy and easily frightened.', 'The timid deer stayed in the trees.'),
    (155, 'Unravel',     'verb',      'To unravel is to come undone, thread by thread.', 'My old scarf began to unravel.'),
    (156, 'Vibrant',     'adjective', 'Vibrant means full of bright colour and life.', 'The market is full of vibrant fruit.'),
    (157, 'Wilderness',  'noun',      'The wilderness is wild land where people do not live.', 'Bears roam the northern wilderness.'),
    (158, 'Yield',       'verb',      'To yield is to give way or let something happen.', 'Cars must yield to the school bus.'),
    (159, 'Zeal',        'noun',      'Zeal is great energy and excitement for something.', 'He studies bugs with real zeal.'),
    (160, 'Astonish',    'verb',      'To astonish is to surprise someone very much.', 'That magic trick will astonish you.'),
    (161, 'Bristle',     'noun',      'A bristle is a short, stiff hair.', 'Every bristle on the brush was worn.'),
    (162, 'Charming',    'adjective', 'Charming means very pleasing and likeable.', 'We visited a charming little town.'),
    (163, 'Dense',       'adjective', 'Dense means packed very close together.', 'A dense fog covered the harbour.'),
    (164, 'Elegant',     'adjective', 'Elegant means graceful and beautifully simple.', 'The swan made an elegant turn.'),
    (165, 'Feeble',      'adjective', 'Feeble means weak and without strength.', 'The old lamp gave a feeble light.'),
    (166, 'Glorious',    'adjective', 'Glorious means wonderful and full of beauty.', 'What a glorious sunny morning!'),
    (167, 'Humble',      'adjective', 'Humble means not bragging about yourself.', 'The humble champion thanked her team.'),
    (168, 'Idle',        'adjective', 'Idle means not doing anything at all.', 'The swings sat idle in the rain.'),
    (169, 'Jubilant',    'adjective', 'Jubilant means feeling and showing great joy.', 'The jubilant team lifted the trophy.'),
    (170, 'Keen',        'adjective', 'Keen means very interested and eager.', 'He is keen to learn the guitar.'),
    (171, 'Linger',      'verb',      'To linger is to stay somewhere longer than needed.', 'We linger by the warm fire.'),
    (172, 'Marvelous',   'adjective', 'Marvelous means amazing and wonderful.', 'We had a marvelous time at camp.'),
    (173, 'Nudge',       'verb',      'To nudge is to push gently with your elbow or nose.', 'The horse gave me a soft nudge.'),
    (174, 'Overjoyed',   'adjective', 'Overjoyed means extremely happy.', 'She was overjoyed to see the puppy.'),
    (175, 'Precious',    'adjective', 'Precious means very valuable or much loved.', 'This photo is precious to me.'),
    (176, 'Quirky',      'adjective', 'Quirky means unusual in a fun way.', 'My uncle has a quirky sense of humour.'),
    (177, 'Rickety',     'adjective', 'Rickety means shaky and likely to break.', 'We crossed a rickety wooden bridge.'),
    (178, 'Sneak',       'verb',      'To sneak is to move quietly so nobody notices.', 'I sneak downstairs for a snack.'),
    (179, 'Tremble',     'verb',      'To tremble is to shake because of cold or fear.', 'My hands tremble before a big test.'),
    (180, 'Uproar',      'noun',      'An uproar is a loud burst of noise and excitement.', 'The winning goal caused an uproar.'),
    (181, 'Vivid',       'adjective', 'Vivid means very bright and very clear.', 'I had a vivid dream about flying.'),
    (182, 'Weave',       'verb',      'To weave is to pass threads over and under to make cloth.', 'We weave paper strips into a mat.'),
    (183, 'Yonder',      'adverb',    'Yonder means over there, farther away.', 'The barn stands yonder past the field.'),
    (184, 'Zest',        'noun',      'Zest is great enjoyment and energy.', 'She sings every song with zest.'),
    (185, 'Abundant',    'adjective', 'Abundant means there is more than enough.', 'Apples are abundant in autumn.'),
    (186, 'Beckon',      'verb',      'To beckon is to wave someone closer.', 'The teacher beckons us to the door.'),
    (187, 'Cascade',     'noun',      'A cascade is a small waterfall.', 'A cascade tumbles down the rocks.'),
    (188, 'Drizzle',     'noun',      'A drizzle is very light rain.', 'A soft drizzle fell all morning.'),
    (189, 'Enchant',     'verb',      'To enchant is to delight someone as if by magic.', 'The puppet show will enchant you.'),
    (190, 'Flourish',    'verb',      'To flourish is to grow well and be healthy.', 'Sunflowers flourish in warm sun.'),
    (191, 'Graceful',    'adjective', 'Graceful means moving in a smooth, lovely way.', 'The dancer made a graceful leap.'),
    (192, 'Hearty',      'adjective', 'Hearty means warm, strong and full of energy.', 'He gave a hearty laugh.'),
    (193, 'Immense',     'adjective', 'Immense means huge in size or amount.', 'An immense crowd filled the square.'),
    (194, 'Jostle',      'verb',      'To jostle is to push against others in a crowd.', 'Fans jostle to see the singer.'),
    (195, 'Kindle',      'verb',      'To kindle is to start a fire or start a feeling.', 'One spark can kindle the campfire.'),
    (196, 'Luminous',    'adjective', 'Luminous means giving off light in the dark.', 'The luminous clock glows at night.'),
    (197, 'Meander',     'verb',      'To meander is to follow a slow, winding path.', 'The river meanders through the valley.'),
    (198, 'Nourish',     'verb',      'To nourish is to give what is needed to grow strong.', 'Milk and fruit nourish your body.'),
    (199, 'Obstacle',    'noun',      'An obstacle is something that blocks your way.', 'We climbed over every obstacle.'),
    (200, 'Plentiful',   'adjective', 'Plentiful means there is a large amount.', 'Fish are plentiful in this lake.'),
    (201, 'Quaver',      'verb',      'To quaver is to shake while you speak or sing.', 'His voice began to quaver.'),
    (202, 'Ravine',      'noun',      'A ravine is a deep, narrow valley.', 'A rope bridge crossed the ravine.'),
    (203, 'Serene',      'adjective', 'Serene means calm and peaceful.', 'The lake was serene at sunrise.'),
    (204, 'Tremendous',  'adjective', 'Tremendous means very great in size or amount.', 'That was a tremendous effort!'),
    (205, 'Unique',      'adjective', 'Unique means the only one of its kind.', 'Every snowflake is unique.'),
    (206, 'Venture',     'verb',      'To venture is to go somewhere new or risky.', 'We venture deeper into the forest.'),
    (207, 'Whimsical',   'adjective', 'Whimsical means playful and full of imagination.', 'She drew a whimsical purple cat.'),
    (208, 'Youthful',    'adjective', 'Youthful means young or full of young energy.', 'Grandpa has a youthful spirit.'),
    (209, 'Zip',         'verb',      'To zip is to move very quickly.', 'Bikes zip along the park path.'),
    (210, 'Adore',       'verb',      'To adore is to love something very much.', 'I adore my little sister.'),
    (211, 'Bewilder',    'verb',      'To bewilder is to confuse someone completely.', 'This giant maze will bewilder anyone.'),
    (212, 'Cherish',     'verb',      'To cherish is to care for something with love.', 'I cherish the stories grandma tells.'),
    (213, 'Dainty',      'adjective', 'Dainty means small, delicate and pretty.', 'She wore a dainty silver ring.'),
    (214, 'Ember',       'noun',      'An ember is a small glowing piece of a fire.', 'One orange ember still glowed.'),
    (215, 'Frolic',      'verb',      'To frolic is to play in a happy, lively way.', 'Lambs frolic in the spring field.'),
    (216, 'Gigantic',    'adjective', 'Gigantic means enormously large.', 'A gigantic wave rolled to shore.'),
    (217, 'Hasty',       'adjective', 'Hasty means done too quickly.', 'A hasty answer is often wrong.'),
    (218, 'Inspire',     'verb',      'To inspire is to give someone a good idea or hope.', 'Her story will inspire the class.'),
    (219, 'Jumble',      'noun',      'A jumble is an untidy mix of things.', 'My toy box is a total jumble.'),
    (220, 'Knack',       'noun',      'A knack is a special skill for doing something.', 'He has a knack for finding lost socks.'),
    (221, 'Lull',        'verb',      'To lull is to make someone calm or sleepy.', 'Soft rain can lull you to sleep.'),
    (222, 'Mingle',      'verb',      'To mingle is to mix together with others.', 'Guests mingle at the birthday party.'),
    (223, 'Nocturnal',   'adjective', 'Nocturnal animals are awake at night.', 'Owls and bats are nocturnal.'),
    (224, 'Ooze',        'verb',      'To ooze is to flow out slowly and thickly.', 'Honey oozes from the tipped jar.'),
    (225, 'Pester',      'verb',      'To pester is to bother someone again and again.', 'Do not pester the sleeping dog.'),
    (226, 'Quarrel',     'noun',      'A quarrel is an angry argument.', 'The quarrel ended with a handshake.'),
    (227, 'Rustle',      'verb',      'To rustle is to make a soft, dry sound.', 'Dry leaves rustle under our feet.'),
    (228, 'Scorch',      'verb',      'To scorch is to burn the surface of something.', 'The hot sun can scorch the grass.'),
    (229, 'Thrive',      'verb',      'To thrive is to grow strong and do very well.', 'Plants thrive with water and light.'),
    (230, 'Utter',       'verb',      'To utter is to say something out loud.', 'He did not utter a single word.'),
    (231, 'Vigorous',    'adjective', 'Vigorous means strong and full of energy.', 'We did a vigorous warm-up.'),
    (232, 'Waddle',      'verb',      'To waddle is to walk with short, rocking steps.', 'Ducks waddle down to the pond.'),
    (233, 'Yelp',        'verb',      'To yelp is to give a short, sharp cry.', 'The puppy gave a surprised yelp.'),
    (234, 'Zealous',     'adjective', 'Zealous means very eager and enthusiastic.', 'He is a zealous football fan.'),
    (235, 'Ajar',        'adjective', 'Ajar means slightly open.', 'The kitchen door was left ajar.'),
    (236, 'Brisk',       'adjective', 'Brisk means quick and full of energy.', 'We took a brisk walk before dinner.'),
    (237, 'Clumsy',      'adjective', 'Clumsy means moving in an awkward way.', 'I felt clumsy in my big boots.'),
    (238, 'Dwindle',     'verb',      'To dwindle is to slowly get smaller.', 'Our snack supply began to dwindle.'),
    (239, 'Exquisite',   'adjective', 'Exquisite means very beautiful and finely made.', 'The exquisite vase is very old.'),
    (240, 'Frantic',     'adjective', 'Frantic means wildly worried and hurried.', 'We made a frantic search for the key.'),
    (241, 'Glum',        'adjective', 'Glum means sad and quiet.', 'He looked glum about the rain.'),
    (242, 'Hoard',       'verb',      'To hoard is to save up a large secret pile.', 'Squirrels hoard nuts for the winter.'),
    (243, 'Intrepid',    'adjective', 'Intrepid means fearless and adventurous.', 'The intrepid explorer sailed north.'),
    (244, 'Jovial',      'adjective', 'Jovial means cheerful and friendly.', 'Our jovial coach always tells jokes.'),
    (245, 'Keepsake',    'noun',      'A keepsake is something you keep to remember someone.', 'This shell is a keepsake from the beach.'),
    (246, 'Lurk',        'verb',      'To lurk is to wait quietly out of sight.', 'A crab can lurk under that rock.'),
    (247, 'Meek',        'adjective', 'Meek means quiet, gentle and not bold.', 'The meek mouse hid behind the box.'),
    (248, 'Notion',      'noun',      'A notion is an idea in your mind.', 'I had a notion to bake some bread.'),
    (249, 'Obedient',    'adjective', 'Obedient means doing what you are told.', 'The obedient dog sat right away.'),
    (250, 'Peril',       'noun',      'Peril is great danger.', 'The sailors faced peril in the storm.'),
    (251, 'Quill',       'noun',      'A quill is a large feather used as a pen.', 'She wrote the letter with a quill.'),
    (252, 'Ramble',      'verb',      'To ramble is to walk or talk on and on.', 'We ramble through the hills all day.'),
    (253, 'Snug',        'adjective', 'Snug means warm and fitting closely.', 'The wool hat felt snug on my head.'),
    (254, 'Tuft',        'noun',      'A tuft is a small bunch of hair or grass.', 'A tuft of fur stuck up on his head.'),
    (255, 'Uncover',     'verb',      'To uncover is to find or reveal something hidden.', 'We uncover a fossil in the sand.'),
    (256, 'Vigilant',    'adjective', 'Vigilant means watching carefully for danger.', 'The vigilant goose guarded the nest.'),
    (257, 'Wince',       'verb',      'To wince is to flinch because something hurts.', 'I wince when I pull off the plaster.'),
    (258, 'Yarn',        'noun',      'Yarn is thick thread used for knitting.', 'The kitten unrolled the ball of yarn.'),
    (259, 'Amble',       'verb',      'To amble is to walk slowly and easily.', 'We amble along the river path.'),
    (260, 'Blaze',       'noun',      'A blaze is a bright, strong fire.', 'The little campfire became a blaze.'),
    (261, 'Cackle',      'verb',      'To cackle is to laugh in a loud, sharp way.', 'The hens cackle in the yard.'),
    (262, 'Delicate',    'adjective', 'Delicate means fine and easily damaged.', 'A delicate web hung in the corner.'),
    (263, 'Elude',       'verb',      'To elude is to escape from someone cleverly.', 'The rabbit can elude the fox.'),
    (264, 'Flimsy',      'adjective', 'Flimsy means thin and weak.', 'The flimsy paper hat tore at once.'),
    (265, 'Grumpy',      'adjective', 'Grumpy means in a bad mood.', 'My cat is grumpy before breakfast.'),
    (266, 'Huddle',      'verb',      'To huddle is to crowd close together.', 'Penguins huddle to stay warm.'),
    (267, 'Impish',      'adjective', 'Impish means playfully naughty.', 'He gave us an impish grin.'),
    (268, 'Jest',        'noun',      'A jest is a joke.', 'He said it only as a jest.'),
    (269, 'Kneel',       'verb',      'To kneel is to go down on your knees.', 'I kneel to tie my shoelace.'),
    (270, 'Lush',        'adjective', 'Lush means thick and full of healthy green plants.', 'The garden is lush after the rain.'),
    (271, 'Mound',       'noun',      'A mound is a small hill or pile.', 'Ants built a mound of sand.'),
    (272, 'Nifty',       'adjective', 'Nifty means clever and useful.', 'That is a nifty little gadget.'),
    (273, 'Outwit',      'verb',      'To outwit is to beat someone by being cleverer.', 'The mouse can outwit the cat.'),
    (274, 'Prowl',       'verb',      'To prowl is to move quietly while hunting.', 'Lions prowl through the tall grass.'),
    (275, 'Quiz',        'noun',      'A quiz is a short test with questions.', 'We had a spelling quiz today.'),
    (276, 'Rejoice',     'verb',      'To rejoice is to feel and show great joy.', 'We rejoice when the rain finally stops.'),
    (277, 'Shrewd',      'adjective', 'Shrewd means clever at judging things.', 'A shrewd shopper compares prices.'),
    (278, 'Tuck',        'verb',      'To tuck is to push something snugly into place.', 'Tuck the blanket under the mattress.'),
    (279, 'Unfurl',      'verb',      'To unfurl is to unroll or spread out.', 'The ship began to unfurl its sails.'),
    (280, 'Vault',       'verb',      'To vault is to jump over something using your hands.', 'He can vault over the low wall.'),
    (281, 'Wistful',     'adjective', 'Wistful means a little sad about something you miss.', 'She gave a wistful look at the sea.'),
    (282, 'Yodel',       'verb',      'To yodel is to sing with quick high and low sounds.', 'Climbers yodel across the valley.'),
    (283, 'Adrift',      'adjective', 'Adrift means floating without any control.', 'The little boat was adrift at sea.'),
    (284, 'Bough',       'noun',      'A bough is a big branch of a tree.', 'An owl sat on the highest bough.'),
    (285, 'Clamber',     'verb',      'To clamber is to climb using hands and feet.', 'We clamber over the wet rocks.'),
    (286, 'Dusk',        'noun',      'Dusk is the time when it starts to get dark.', 'Bats come out at dusk.'),
    (287, 'Earnest',     'adjective', 'Earnest means serious and sincere.', 'He made an earnest promise.'),
    (288, 'Fond',        'adjective', 'Fond means having warm, loving feelings.', 'I am fond of rainy days.'),
    (289, 'Gulp',        'verb',      'To gulp is to swallow quickly in big amounts.', 'He gulps his milk far too fast.'),
    (290, 'Haven',       'noun',      'A haven is a safe, peaceful place.', 'The library is my quiet haven.'),
    (291, 'Inkling',     'noun',      'An inkling is a small hint or idea about something.', 'I had an inkling about the surprise.'),
    (292, 'Jaunt',       'noun',      'A jaunt is a short trip for fun.', 'We took a jaunt to the lighthouse.'),
    (293, 'Knoll',       'noun',      'A knoll is a small round hill.', 'We picnic on the grassy knoll.'),
    (294, 'Limp',        'verb',      'To limp is to walk unevenly because of a sore leg.', 'The tired dog began to limp home.'),
    (295, 'Mend',        'verb',      'To mend is to fix something broken.', 'Dad will mend the torn kite.'),
    (296, 'Nook',        'noun',      'A nook is a small cosy corner.', 'I read in the nook by the window.'),
    (297, 'Overcast',    'adjective', 'Overcast means the sky is covered with clouds.', 'The morning was grey and overcast.'),
    (298, 'Perch',       'verb',      'To perch is to sit on the edge of something high.', 'Sparrows perch on the wire.'),
    (299, 'Quicken',     'verb',      'To quicken is to become faster.', 'My steps quicken near home.'),
    (300, 'Roost',       'verb',      'To roost is to settle down to sleep, like a bird.', 'The chickens roost at sunset.'),
    (301, 'Scrumptious', 'adjective', 'Scrumptious means extremely tasty.', 'That was a scrumptious pudding.'),
    (302, 'Trickle',     'verb',      'To trickle is to flow in a thin, slow stream.', 'Water trickles from the old tap.'),
    (303, 'Uneven',      'adjective', 'Uneven means not flat or not equal.', 'The uneven path made me trip.'),
    (304, 'Vex',         'verb',      'To vex is to annoy someone.', 'Buzzing flies vex the horses.'),
    (305, 'Wharf',       'noun',      'A wharf is a platform where boats load and unload.', 'Fishing boats tie up at the wharf.'),
    (306, 'Yolk',        'noun',      'The yolk is the yellow middle part of an egg.', 'The yolk broke in the frying pan.'),
    (307, 'Awe',         'noun',      'Awe is a feeling of great wonder and respect.', 'We stared at the canyon in awe.'),
    (308, 'Baffle',      'verb',      'To baffle is to puzzle someone completely.', 'This riddle will baffle the class.'),
    (309, 'Cling',       'verb',      'To cling is to hold on tightly.', 'Baby monkeys cling to their mothers.'),
    (310, 'Dwell',       'verb',      'To dwell is to live in a place.', 'Owls dwell in the old barn.'),
    (311, 'Elated',      'adjective', 'Elated means very happy and proud.', 'She felt elated after the race.'),
    (312, 'Fumble',      'verb',      'To fumble is to handle something clumsily.', 'I fumble the ball and drop it.'),
    (313, 'Gnaw',        'verb',      'To gnaw is to chew on something for a long time.', 'Beavers gnaw through thick trees.'),
    (314, 'Hasten',      'verb',      'To hasten is to hurry.', 'We hasten to finish before dark.'),
    (315, 'Immerse',     'verb',      'To immerse is to put something all the way into a liquid.', 'Immerse the brush in the water.'),
    (316, 'Jitters',     'noun',      'Jitters are nervous, shaky feelings.', 'I get the jitters before a show.'),
    (317, 'Knead',       'verb',      'To knead is to press and fold dough with your hands.', 'We knead the bread dough together.'),
    (318, 'Latch',       'noun',      'A latch is a small catch that holds a door shut.', 'Lift the latch to open the gate.'),
    (319, 'Mimic',       'verb',      'To mimic is to copy the way someone acts or sounds.', 'Parrots mimic human voices.'),
    (320, 'Nurture',     'verb',      'To nurture is to care for something as it grows.', 'We nurture the seedlings each day.'),
    (321, 'Onward',      'adverb',    'Onward means continuing forward.', 'The tired team marched onward.'),
    (322, 'Placid',      'adjective', 'Placid means calm and still.', 'The placid pond looked like glass.'),
    (323, 'Quirk',       'noun',      'A quirk is an odd little habit.', 'Humming is one of his quirks.'),
    (324, 'Rouse',       'verb',      'To rouse is to wake someone up.', 'The alarm will rouse the whole house.'),
    (325, 'Squabble',    'noun',      'A squabble is a small, noisy argument.', 'The gulls had a squabble over chips.'),
    (326, 'Tussle',      'noun',      'A tussle is a playful struggle.', 'The puppies had a friendly tussle.'),
    (327, 'Unwind',      'verb',      'To unwind is to relax after being busy.', 'We unwind with a story at night.'),
    (328, 'Vessel',      'noun',      'A vessel is a ship or a container.', 'The vessel sailed into the harbour.'),
    (329, 'Wade',        'verb',      'To wade is to walk through shallow water.', 'We wade across the little stream.'),
    (330, 'Yearly',      'adjective', 'Yearly means happening once every year.', 'The yearly fair comes in June.'),
    (331, 'Zippy',       'adjective', 'Zippy means fast and full of energy.', 'She rode a zippy little scooter.'),
    (332, 'Aroma',       'noun',      'An aroma is a pleasant smell.', 'The aroma of bread filled the house.'),
    (333, 'Bellow',      'verb',      'To bellow is to shout in a deep, loud voice.', 'The coach bellows from the sideline.'),
    (334, 'Chuckle',     'verb',      'To chuckle is to laugh quietly.', 'Dad chuckles at his own jokes.'),
    (335, 'Dappled',     'adjective', 'Dappled means covered with spots of colour or light.', 'Dappled sunlight fell on the path.'),
    (336, 'Excel',       'verb',      'To excel is to be very good at something.', 'She excels at solving puzzles.'),
    (337, 'Faint',       'adjective', 'Faint means very weak or hard to notice.', 'I heard a faint knock at the door.'),
    (338, 'Gallop',      'verb',      'To gallop is to run fast like a horse.', 'The little pony began to gallop.'),
    (339, 'Heap',        'noun',      'A heap is an untidy pile.', 'A heap of leaves filled the yard.'),
    (340, 'Inquire',     'verb',      'To inquire is to ask about something.', 'We inquire about the missing book.'),
    (341, 'Jut',         'verb',      'To jut is to stick out.', 'Sharp rocks jut out from the cliff.'),
    (342, 'Keel',        'noun',      'A keel is the long bar along the bottom of a boat.', 'The keel scraped the sandy bottom.'),
    (343, 'Lurch',       'verb',      'To lurch is to move with a sudden jerk.', 'The old bus gave a big lurch.'),
    (344, 'Muffle',      'verb',      'To muffle is to make a sound quieter.', 'Thick snow can muffle every noise.'),
    (345, 'Nimbly',      'adverb',    'Nimbly means quickly and lightly.', 'The gymnast landed nimbly.'),
    (346, 'Ornate',      'adjective', 'Ornate means covered with fancy decoration.', 'The ornate gate was made of iron.'),
    (347, 'Peer',        'verb',      'To peer is to look closely and hard.', 'We peer into the dark old well.'),
    (348, 'Quicksand',   'noun',      'Quicksand is loose wet sand that you sink into.', 'The explorers avoided the quicksand.'),
    (349, 'Ragged',      'adjective', 'Ragged means torn and worn out.', 'His ragged coat had many holes.'),
    (350, 'Sag',         'verb',      'To sag is to sink or droop in the middle.', 'The old shelf began to sag.'),
    (351, 'Tepid',       'adjective', 'Tepid means only slightly warm.', 'The tepid soup was not very tasty.'),
    (352, 'Uphill',      'adjective', 'Uphill means going up a slope.', 'The last uphill part was hard.'),
    (353, 'Veer',        'verb',      'To veer is to change direction suddenly.', 'The bike had to veer around a hole.'),
    (354, 'Whittle',     'verb',      'To whittle is to carve wood with a knife.', 'Grandpa likes to whittle small birds.'),
    (355, 'Yank',        'verb',      'To yank is to pull hard and suddenly.', 'I yank the stuck door open.'),
    (356, 'Zap',         'verb',      'To zap is to hit something with sudden energy.', 'The wand seemed to zap the box.'),
    (357, 'Aglow',       'adjective', 'Aglow means shining with a warm light.', 'The room was aglow with candles.'),
    (358, 'Bustle',      'noun',      'Bustle is busy, noisy movement.', 'The station is full of bustle.'),
    (359, 'Coax',        'verb',      'To coax is to gently persuade someone.', 'We coax the puppy out of hiding.'),
    (360, 'Dart',        'verb',      'To dart is to move suddenly and quickly.', 'Small fish dart under the dock.'),
    (361, 'Endure',      'verb',      'To endure is to keep going through something hard.', 'We endure the long, cold walk.'),
    (362, 'Frost',       'noun',      'Frost is a thin white layer of ice.', 'Frost covered the morning grass.'),
    (363, 'Glee',        'noun',      'Glee is a feeling of great delight.', 'The children shouted with glee.'),
    (364, 'Hearth',      'noun',      'A hearth is the floor in front of a fireplace.', 'The dog sleeps by the warm hearth.'),
    (365, 'Jubilee',     'noun',      'A jubilee is a special anniversary celebration.', 'The town held a summer jubilee.'),
    (366, 'Triumphant',  'adjective', 'Triumphant means feeling great after winning.', 'The triumphant team cheered loudly.')
ON CONFLICT (day_of_year) DO NOTHING;
